
server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1
    database: 3
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        min-idle: 10
        max-wait: 1000ms
  jackson:
    date-format: yyyy-MM-dd
    locale: zh_CN
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /test
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 10

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.bdqn.seckill.entity
  configuration:
    map-underscore-to-camel-case: true


